### ISSUE TITLE
windows 下 路径报错

### ISSUE THREAD

**Issue by godkun** [pandolajs/pandora-boilerplate-wechat#2]
这块我就不详细写了，

用 windows 开发时，alias 报错。

看dist 目录中的 文件路径，发现都是  '..\..\utils\index'

在windows下，alias 路径解析的有问题。

你们用的时候没有出现这种问题吗？

如果有问题，gulp-plugin-alias 文件可能要修改了

**Comment by dancon** [comment]
windows 下没有完整测试过 ~ 现在手头也没有 windows 环境，明天晚上看下，给你带来麻烦非常抱歉 ~

**Comment by godkun** [comment]
哈哈哈，我现在真正魔改你的插件。。windows 各种坑啊。不只这一个问题。

**Comment by dancon** [comment]
@godkun 你的 node 版本是多少？

**Comment by godkun** [comment]
10.15.1

**Comment by godkun** [comment]
你们要是有 widows 电脑 的话，可以跑一下，就是你们自己的这套代码，放到开发者工具上，就直接报错了。而且多进行几次 npm start  还会爆其他的错误，这边我的解决方案，在build的时候，先把 dist 删除。这样多次start 报错的问题就没了。

目前路径问题只解决了普通的js文件引入，对于npm包的路径引入，比如实现async await的包输出的js路径， 暂时没有解决掉。就算我dist目录下的路径已经完全和正常路径一样了，还是会报错。

你有空了可以看看。

node 版本也属于稳定版

**Comment by dancon** [comment]
本周一定修复

**Comment by godkun** [comment]
好嘞，加油哈

**Comment by dancon** [comment]
已经修复，请使用 0.5.1 进行项目初始化

![image](https://user-images.githubusercontent.com/6836599/54256888-71512680-4598-11e9-98b5-6123d092e840.png)

@godkun

**Comment by godkun** [comment]
恩恩，谢谢，我来看一下

**Comment by godkun** [comment]
这块引入 安装的npm包。比如 ramda.js 是安装后，直接在js文件中按照默认的方式来引入就可以使用么，还是说需要在buil.config里面进行配置
