### ISSUE TITLE
希望添加快速创建组件和页面的命令

### ISSUE THREAD

**Issue by liangei** [pandolajs/pandora-boilerplate-wechat#6]
希望功能是这样的
运行 npm create page pagename
就可以在src的pages文件夹创建pagename的文件夹
包含以下模板
index.styl
index.json
index.wxml
index.js

运行 npm create com comname
同上面创建page一样

**Comment by dancon** [comment]
@liangei 可以通过 pa create page yourPageName 就可以创建，模板可以自定义，请参考 [文档](https://github.com/pandolajs/pandora-cli#%E5%88%9B%E5%BB%BA%E6%A0%B7%E6%9D%BF%E4%BB%A3%E7%A0%81-pa-create-%E6%88%96%E8%80%85-pa-c)
